# Generated by Django 3.0.4 on 2021-03-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210319_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('AC', 'active'), ('PA', 'paused'), ('FI', 'finished')], default='AC', max_length=2),
        ),
    ]
