# Generated by Django 3.0.4 on 2021-03-22 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='won',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
